export interface ContentRun {
  text: string;
  bold: boolean;
}

export interface ContentBlock {
  type: "heading-2" | "heading-3" | "paragraph";
  runs: ContentRun[];
}

function inlineRuns(element: Element): ContentRun[] {
  const runs: ContentRun[] = [];

  const visit = (node: Node, bold = false) => {
    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent ?? "";
      if (text) runs.push({ text, bold });
      return;
    }
    if (!(node instanceof Element)) return;
    const tag = node.tagName.toLocaleLowerCase();
    const nextBold = bold || tag === "strong" || tag === "b";
    for (const child of node.childNodes) visit(child, nextBold);
  };

  for (const child of element.childNodes) visit(child);
  return runs;
}

function legacyBlocks(content: string): ContentBlock[] {
  return content
    .split(/\n{2,}/)
    .map((text) => text.trim())
    .filter(Boolean)
    .map((text) => ({
      type: "paragraph" as const,
      runs: [{ text, bold: false }],
    }));
}

/** Parse only the semantic HTML subset generated by the PDF importer. */
export function parseContentBlocks(content: string): ContentBlock[] {
  if (
    !/<(?:h2|h3|p|strong)\b/i.test(content) ||
    typeof DOMParser === "undefined"
  ) {
    return legacyBlocks(content);
  }

  const document = new DOMParser().parseFromString(content, "text/html");
  const blocks: ContentBlock[] = [];
  for (const element of document.body.children) {
    const tag = element.tagName.toLocaleLowerCase();
    if (tag !== "h2" && tag !== "h3" && tag !== "p") continue;
    const runs = inlineRuns(element);
    if (!runs.some((run) => run.text.trim())) continue;
    blocks.push({
      type:
        tag === "h2"
          ? "heading-2"
          : tag === "h3"
            ? "heading-3"
            : "paragraph",
      runs,
    });
  }
  return blocks.length > 0
    ? blocks
    : legacyBlocks(document.body.textContent ?? content);
}
